relationships:
  - name: apmApplicationHostsOnAzureFunctionsApp
    version: "1"
    origins:
      - Azure Integration
    conditions:
      - attribute: entity.type
        anyOf: [ "AZUREFUNCTIONSAPP" ]
      - attribute: azure.resourceId
        present: true
        regex: '^/subscriptions/[^/]+/resourceGroups/[^/]+/providers/Microsoft.Web/sites/[^/]+$'
    relationship:
      expires: P75M
      relationshipType: HOSTS
      source:
        lookupGuid:
          candidateCategory: APMAPPLICATION
          fields:
            - field: resourceId
              attribute: azure.resourceId
      target:
        extractGuid:
          attribute: entity.guid
          entityType:
            value: AZUREFUNCTIONSAPP