relationships:
  - name: apmApplicationCallsAzureRedisCache
    version: "1"
    origins:
      - Distributed Tracing
    conditions:
      - attribute: eventType
        anyOf: [ "Span" ]
      - attribute: db.system 
        anyOf: [ "redis" ]
      - attribute: server.address 
        regex: '^[a-z0-9\-]+\.redis\.cache\.windows\.net$'
        present: true
      - attribute: server.port 
        present: true
    relationship:
      expires: P75M 
      relationshipType: CALLS 
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: AZUREREDISCACHE
          fields:
            - field: endpoint
              attribute: server.address
            - field: port
              attribute: server.port