relationships:
  - name: apmApplicationCallsAzureMySqlFlexibleServer
    version: "1"
    origins:
      - Distributed Tracing 
    conditions:
      - attribute: eventType
        anyOf: [ "Span" ]
      - attribute: db.system 
        anyOf: [ "mysql" ]
      - attribute: server.address 
        regex: '^[a-z0-9\-]+\.mysql\.database\.azure\.com$'
        present: true
      - attribute: db.instance
        present: true
    relationship:
      expires: P75M
      relationshipType: CALLS 
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: DATABASE
          fields:
            - field: endpoint
              attribute: server.address 